version: '3'
services:
  mqtt:
    restart: always
    build: .
    container_name: 'mqtt'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./python:/root/python
    env_file:
      - app.env
    entrypoint:
      - python
      - python/mqtt.py
